# Generated by Django 2.1 on 2018-08-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '__first__'),
        ('driver', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(auto_created=True, max_length=50, unique=True)),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('0', 'wait'), ('1', 'ongoing'), ('2', 'completed')], max_length=5)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer.User')),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='driver.Driver')),
            ],
        ),
    ]
