# Generated by Django 2.1 on 2018-08-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rides',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='rides',
            old_name='driver_id',
            new_name='driver',
        ),
    ]
