# Generated by Django 2.1 on 2018-08-11 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180811_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rides',
            name='request_id',
        ),
    ]
